variable "cidr_block" { }
variable "vpc_name" {   }
variable "public_cidr_block" { }
variable "private_cidr_block" { }
variable "azs" { }
variable "ami" { }
variable "instance_type" { }
variable "key_name" { }
variable "private_ip" { }